!/bin/bash
while :
do
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(1,1);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(1,220);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(1,440);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 5
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(310,1);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(620,1);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(930,1);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 5
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(930,220);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(620,220);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(310,220);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 5
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(930,440);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(620,440);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(310,440);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 20
apt-get clean
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(50,50);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(50,270);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(50,490);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 5
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(360,50);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(670,50);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(980,50);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 5
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(980,270);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(670,270);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(360,270);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 5
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(980,490);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(670,490);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 1
google-chrome --user-data-dir=/home/chrome --app="data:text/html,<html><body><script>window.moveTo(360,490);window.resizeTo(300,200);window.location='https://t.co/jgbIIRljvt';</script></body></html>" --no-sandbox --disable-session--crashed-bubble --incognito & sleep 20
apt-get clean
done
