#!/bin/bash
while :
do
firefox & sleep 5
firefox http://atozgames.me & sleep 15
firefox http://atozgames.me & sleep 15
firefox http://atozgames.me & sleep 25
pkill --oldest firefox
apt-get clean
sleep 5
done
